branch-defaults:
  docker:
    environment: speakeasy-prod
    group_suffix: null
global:
  application_name: speakeasy
  default_ec2_keyname: speakeasy
  default_platform: Docker 1.11.2
  default_region: us-east-1
  profile: bf-openlab
  sc: git
