branch-defaults:
  master:
    environment: speakeasy-dev
global:
  application_name: speakeasy
  branch: null
  default_ec2_keyname: cathy
  default_platform: Docker 1.11.2
  default_region: us-east-1
  profile: bf-openlab
  repository: null
  sc: git
